"use client";
import { useState } from "react";

export default function Home() {
  const [file, setFile] = useState(null);
  const [status, setStatus] = useState("idle");
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);
  const [companyName, setCompanyName] = useState("");
  const [industry, setIndustry] = useState("Professional Services");
  const [employees, setEmployees] = useState("100");
  const [dragging, setDragging] = useState(false);
  const [activeTab, setActiveTab] = useState("summary");
  const [subStatus, setSubStatus] = useState("active"); // "loading" | "active" | "inactive"
  const [subEmail, setSubEmail] = useState("");
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [onceLoading, setOnceLoading] = useState(false);

  const handleOneTimePurchase = async () => {
    setOnceLoading(true);
    try {
      const res = await fetch("/api/checkout-once", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: subEmail || undefined }),
      });
      const data = await res.json();
      if (data.url) window.location.href = data.url;
    } catch {
      setOnceLoading(false);
    }
  };


  const handleSubscribe = async (priceId) => {
    setCheckoutLoading(true);
    try {
      const res = await fetch("/api/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ priceId, email: subEmail || undefined }),
      });
      const data = await res.json();
      if (data.url) window.location.href = data.url;
    } catch {
      setCheckoutLoading(false);
    }
  };

  const handleManageBilling = async () => {
    const res = await fetch("/api/portal", { method: "POST" });
    const data = await res.json();
    if (data.url) window.location.href = data.url;
  };

  const gold = "#c9a84c";
  const card = { background:"rgba(255,255,255,0.04)", border:"1px solid rgba(255,255,255,0.08)", borderRadius:"16px", padding:"24px", marginBottom:"16px" };
  const lbl = { fontSize:"11px", fontWeight:"600", color:"rgba(255,255,255,0.35)", letterSpacing:"0.07em", marginBottom:"14px", display:"block" };
  const fmt = (n) => "£" + Number(n).toLocaleString();

  const handleDrop = (e) => { e.preventDefault(); setDragging(false); const f = e.dataTransfer.files[0]; if(f) setFile(f); };

  const handleTranslate = async () => {
    if (!file) return;
    setStatus("loading"); setError(null); setResult(null);
    const fd = new FormData(); fd.append("file", file);
    try {
      const res = await fetch("/api/translate", { method:"POST", body:fd });
      const data = await res.json();
      if (data.error === "subscription_required") { setSubStatus("inactive"); setStatus("idle"); }
      else if (data.error) { setError(data.error); setStatus("error"); }
      else { setResult(data); setStatus("done"); setActiveTab("summary"); }
    } catch { setError("Something went wrong."); setStatus("error"); }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result.summary + "\n\nFAQs:\n" + result.faqs.map((f,i)=>`Q${i+1}: ${f.q}\nA: ${f.a}`).join("\n\n"));
    setCopied(true); setTimeout(()=>setCopied(false),2000);
  };

  const handleDownload = () => {
    const r = result;
    const t = [
      `${companyName||"Company"} — PsychFlo Policy Intelligence Report`,
      `Generated: ${new Date().toLocaleDateString("en-GB")}`,
      `CLASSIFICATION: CONFIDENTIAL`,
      ``,
      `EXECUTIVE SUMMARY`,
      r.boardReport.executiveSummary,
      ``,
      `KEY FINANCIAL RISKS`,
      ...r.boardReport.keyRisks.map(k=>`• ${k.risk}: ${k.financial} [${k.urgency}]`),
      ``,
      `TRIBUNAL RISK SCORE: ${r.tribunalRisk.score}/100 — ${r.tribunalRisk.label}`,
      `Estimated cost per case: ${fmt(r.tribunalRisk.estimatedCost)}`,
      ``,
      `PRODUCTIVITY LOSS: ${fmt(r.productivityLoss.annualCostGBP)}/year`,
      `TURNOVER EXPOSURE: ${fmt(r.retentionCalculator.totalExposure)}`,
      `POLICY ROI POTENTIAL: ${r.policyROI.roiMultiplier}x in ${r.policyROI.timeToROI}`,
      ``,
      `PLAIN-LANGUAGE SUMMARY`,
      r.summary,
      ``,
      `EMPLOYEE FAQs`,
      ...r.faqs.map((f,i)=>`Q${i+1}: ${f.q}\nA: ${f.a}`),
      ``,
      `BOARD RECOMMENDATION`,
      r.boardReport.recommendation,
      ``,
      `--- Generated by PsychFlo Policy Intelligence Platform ---`
    ].join("\n");
    const blob = new Blob([t],{type:"text/plain"});
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href=url; a.download=`${companyName||"policy"}-psychflo-board-report.txt`; a.click();
  };

  const handleReset = () => { setFile(null); setStatus("idle"); setResult(null); setError(null); setCopied(false); };

  const Bar = ({value, color="#c9a84c", height=6}) => (
    <div style={{background:"rgba(255,255,255,0.07)", borderRadius:"999px", height, overflow:"hidden"}}>
      <div style={{width:`${Math.min(value,100)}%`, height:"100%", background:color, borderRadius:"999px"}}/>
    </div>
  );

  const StatCard = ({label, value, color, sub}) => (
    <div style={{background:"rgba(255,255,255,0.04)", border:"1px solid rgba(255,255,255,0.08)", borderRadius:"12px", padding:"14px", textAlign:"center"}}>
      <div style={{fontSize:"20px", fontWeight:"700", color:color||"#f8fafc", marginBottom:"3px"}}>{value}</div>
      <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>{label}</div>
      {sub && <div style={{fontSize:"10px", color:"rgba(255,255,255,0.2)", marginTop:"2px"}}>{sub}</div>}
    </div>
  );

  const tabs = [
    {id:"summary",label:"Summary"},
    {id:"tribunal",label:"Tribunal Risk"},
    {id:"rewriter",label:"Policy Rewriter"},
    {id:"comprehension",label:"Comprehension AI"},
    {id:"competitor",label:"Benchmarks"},
    {id:"retention",label:"Retention ROI"},
    {id:"regulatory",label:"Regulatory"},
    {id:"languages",label:"Languages"},
    {id:"board",label:"Board Report"},
    {id:"forecast",label:"ML Forecast"},
    {id:"productivity",label:"Productivity"},
    {id:"burnout",label:"Burnout"},
    {id:"morale",label:"Morale"},
    {id:"dei",label:"DEI"},
    {id:"cognitive",label:"Cognitive Load"},
    {id:"psychology",label:"Psych Safety"},
    {id:"compliance",label:"Compliance"},
    {id:"bias",label:"Bias"},
    {id:"improve",label:"Improvements"},
  ];

  return (
    <div style={{minHeight:"100vh", background:"linear-gradient(135deg,#0a0f1e 0%,#0f172a 40%,#1a0a2e 100%)", fontFamily:"system-ui,-apple-system,sans-serif"}}>

      <div style={{borderBottom:"1px solid rgba(255,255,255,0.07)", padding:"14px 32px", display:"flex", alignItems:"center", justifyContent:"space-between", background:"rgba(0,0,0,0.2)"}}>
        <div style={{display:"flex", alignItems:"center", gap:"12px"}}>
          <img src="/logo.png" alt="PsychFlo" style={{width:"34px", height:"34px", objectFit:"contain", filter:"invert(1) sepia(1) saturate(2) hue-rotate(5deg) brightness(0.85)"}}/>
          <span style={{color:"#f8fafc", fontWeight:"700", fontSize:"16px", letterSpacing:"-0.01em"}}>PsychFlo</span>
          <span style={{color:"rgba(255,255,255,0.25)", fontSize:"13px"}}>/ Policy Intelligence Platform</span>
        </div>
        <div style={{display:"flex", alignItems:"center", gap:"10px"}}>
          <span style={{fontSize:"12px", color:"rgba(255,255,255,0.25)"}}>19 AI models · Org Psychology · ML Forecasting</span>
          {subStatus === "active" ? (
            <>
              <div style={{background:"rgba(16,185,129,0.12)", border:"1px solid rgba(16,185,129,0.25)", color:"#6ee7b7", fontSize:"11px", fontWeight:"700", padding:"4px 10px", borderRadius:"999px"}}>PRO</div>
              <button onClick={handleManageBilling} style={{background:"rgba(255,255,255,0.05)", border:"1px solid rgba(255,255,255,0.1)", color:"rgba(255,255,255,0.4)", fontSize:"11px", padding:"4px 12px", borderRadius:"999px", cursor:"pointer"}}>Manage billing</button>
            </>
          ) : (
            <div style={{background:"rgba(201,168,76,0.15)", border:"1px solid rgba(201,168,76,0.3)", color:gold, fontSize:"11px", fontWeight:"700", padding:"4px 10px", borderRadius:"999px"}}>BETA</div>
          )}
        </div>
      </div>

      <div style={{maxWidth:"820px", margin:"0 auto", padding:"48px 24px"}}>

        {subStatus === "loading" && (
          <div style={{ textAlign: "center", padding: "80px 0" }}>
            <div style={{ width: "36px", height: "36px", border: `3px solid rgba(201,168,76,0.15)`, borderTop: `3px solid ${gold}`, borderRadius: "50%", margin: "0 auto", animation: "spin 1s linear infinite" }} />
            <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
          </div>
        )}

        {subStatus === "inactive" && (
          <div>
            <div style={{ marginBottom: "48px", textAlign: "center" }}>
              <div style={{ display: "inline-flex", alignItems: "center", gap: "6px", background: "rgba(201,168,76,0.1)", border: "1px solid rgba(201,168,76,0.2)", color: gold, fontSize: "11px", fontWeight: "700", padding: "5px 14px", borderRadius: "999px", marginBottom: "18px", letterSpacing: "0.06em" }}>
                SUBSCRIPTION REQUIRED
              </div>
              <h1 style={{ fontSize: "36px", fontWeight: "800", color: "#f8fafc", margin: "0 0 14px", lineHeight: "1.15", letterSpacing: "-0.03em" }}>
                Unlock Full Policy Intelligence
              </h1>
              <p style={{ fontSize: "15px", color: "rgba(255,255,255,0.4)", margin: "0 auto", lineHeight: "1.7", maxWidth: "520px" }}>
                19 AI models · Tribunal risk scoring · Automatic rewriting · Board-ready reports · ML forecasting
              </p>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: "14px", marginBottom: "32px", maxWidth: "1100px", margin: "0 auto 32px" }}>
              {[
                {
                  name: "Starter", price: "£100", period: "/month", desc: "Fewer than 50 employees",
                  features: ["Up to 10 policy analyses/mo", "All 19 AI analysis modules", "Tribunal risk scoring", "Auto policy rewriter", "Board-ready reports", "Email support"],
                  priceId: process.env.NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID || "price_starter",
                  highlight: false,
                  badge: null,
                },
                {
                  name: "SME", price: "£300", period: "/month", desc: "Up to 500 employees",
                  features: ["Unlimited policy analyses", "All 19 AI analysis modules", "Tribunal risk scoring", "Auto policy rewriter", "Board-ready reports", "Regulatory change alerts", "Email support"],
                  priceId: process.env.NEXT_PUBLIC_STRIPE_SME_PRICE_ID || "price_sme",
                  highlight: false,
                  badge: null,
                },
                {
                  name: "Multi-Enterprise", price: "£700", period: "/month", desc: "Up to 5,000 employees",
                  features: ["Everything in SME", "Multi-site policy management", "Unlimited team seats", "Custom DEI benchmarking", "API access", "White-label reports", "Priority support"],
                  priceId: process.env.NEXT_PUBLIC_STRIPE_ENTERPRISE_PRICE_ID || "price_enterprise",
                  highlight: true,
                  badge: "MOST POPULAR",
                },
                {
                  name: "Large Enterprise", price: "£1,000", period: "/month", desc: "5,000+ employees",
                  features: ["Everything in Multi-Enterprise", "Unlimited policies & sites", "Dedicated account manager", "Custom AI model tuning", "SLA guarantee", "On-boarding & training", "Legal review integration"],
                  priceId: process.env.NEXT_PUBLIC_STRIPE_LARGE_PRICE_ID || "price_large",
                  highlight: false,
                  badge: null,
                },
              ].map((plan) => (
                <div key={plan.name} style={{ background: plan.highlight ? "rgba(201,168,76,0.06)" : "rgba(255,255,255,0.04)", border: plan.highlight ? `1px solid rgba(201,168,76,0.3)` : "1px solid rgba(255,255,255,0.08)", borderRadius: "20px", padding: "28px", display: "flex", flexDirection: "column" }}>
                  {plan.badge && (
                    <div style={{ display: "inline-flex", alignSelf: "flex-start", background: `rgba(201,168,76,0.15)`, border: `1px solid rgba(201,168,76,0.3)`, color: gold, fontSize: "10px", fontWeight: "700", padding: "3px 10px", borderRadius: "999px", marginBottom: "16px", letterSpacing: "0.07em" }}>{plan.badge}</div>
                  )}
                  <div style={{ fontSize: "14px", fontWeight: "700", color: "#f8fafc", marginBottom: "4px" }}>{plan.name}</div>
                  <div style={{ fontSize: "11px", color: "rgba(255,255,255,0.3)", marginBottom: "16px" }}>{plan.desc}</div>
                  <div style={{ display: "flex", alignItems: "baseline", gap: "4px", marginBottom: "24px" }}>
                    <span style={{ fontSize: "32px", fontWeight: "800", color: plan.highlight ? gold : "#f8fafc" }}>{plan.price}</span>
                    <span style={{ fontSize: "13px", color: "rgba(255,255,255,0.35)" }}>{plan.period}</span>
                  </div>
                  <div style={{ flex: 1, marginBottom: "24px" }}>
                    {plan.features.map((f, i) => (
                      <div key={i} style={{ display: "flex", gap: "10px", alignItems: "center", marginBottom: "10px" }}>
                        <span style={{ color: "#10b981", fontSize: "13px", flexShrink: 0 }}>✓</span>
                        <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.5)" }}>{f}</span>
                      </div>
                    ))}
                  </div>
                  <button
                    onClick={() => handleSubscribe(plan.priceId)}
                    disabled={checkoutLoading}
                    style={{ background: plan.highlight ? `linear-gradient(135deg,${gold},#f0d080)` : "rgba(255,255,255,0.08)", border: plan.highlight ? "none" : "1px solid rgba(255,255,255,0.12)", color: plan.highlight ? "#0f172a" : "#f8fafc", padding: "13px", borderRadius: "10px", fontSize: "14px", fontWeight: "800", cursor: checkoutLoading ? "wait" : "pointer", width: "100%", opacity: checkoutLoading ? 0.7 : 1 }}
                  >
                    {checkoutLoading ? "Redirecting…" : `Start ${plan.name}`}
                  </button>
                </div>
              ))}
            </div>

            <div style={{ display: "flex", alignItems: "center", gap: "16px", maxWidth: "600px", margin: "0 auto 28px" }}>
              <div style={{ flex: 1, height: "1px", background: "rgba(255,255,255,0.07)" }} />
              <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.2)", whiteSpace: "nowrap" }}>or pay once, no subscription</span>
              <div style={{ flex: 1, height: "1px", background: "rgba(255,255,255,0.07)" }} />
            </div>

            <div style={{ maxWidth: "420px", margin: "0 auto 32px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "20px", padding: "28px", display: "flex", gap: "24px", alignItems: "center" }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: "13px", fontWeight: "700", color: "#f8fafc", marginBottom: "4px" }}>Single Report</div>
                <div style={{ fontSize: "11px", color: "rgba(255,255,255,0.3)", marginBottom: "14px" }}>One full analysis, no commitment</div>
                <div style={{ display: "flex", flexDirection: "column", gap: "7px" }}>
                  {["Full 19-module AI analysis", "Tribunal risk + DEI scoring", "Board-ready report download", "Valid for 7 days after purchase"].map((f, i) => (
                    <div key={i} style={{ display: "flex", gap: "8px", alignItems: "center" }}>
                      <span style={{ color: "#10b981", fontSize: "12px" }}>✓</span>
                      <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.4)" }}>{f}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div style={{ textAlign: "center", flexShrink: 0 }}>
                <div style={{ fontSize: "32px", fontWeight: "800", color: "#f8fafc", lineHeight: 1 }}>£49</div>
                <div style={{ fontSize: "11px", color: "rgba(255,255,255,0.3)", marginBottom: "14px" }}>one-time</div>
                <button
                  onClick={handleOneTimePurchase}
                  disabled={onceLoading}
                  style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.14)", color: "#f8fafc", padding: "10px 20px", borderRadius: "10px", fontSize: "13px", fontWeight: "700", cursor: onceLoading ? "wait" : "pointer", whiteSpace: "nowrap", opacity: onceLoading ? 0.7 : 1 }}
                >
                  {onceLoading ? "Redirecting…" : "Buy report"}
                </button>
              </div>
            </div>

            <div style={{ maxWidth: "360px", margin: "0 auto", textAlign: "center" }}>
              <input
                type="email"
                placeholder="Your work email (optional)"
                value={subEmail}
                onChange={(e) => setSubEmail(e.target.value)}
                style={{ width: "100%", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "8px", padding: "10px 14px", color: "#f8fafc", fontSize: "13px", outline: "none", boxSizing: "border-box", marginBottom: "12px" }}
              />
              <p style={{ fontSize: "11px", color: "rgba(255,255,255,0.2)" }}>Secure payment via Stripe · Cancel anytime · No contracts</p>
            </div>
          </div>
        )}

        {subStatus === "active" && status === "idle" && (
          <div>
            <div style={{marginBottom:"40px"}}>
              <div style={{display:"inline-flex", alignItems:"center", gap:"6px", background:"rgba(201,168,76,0.1)", border:"1px solid rgba(201,168,76,0.2)", color:gold, fontSize:"11px", fontWeight:"700", padding:"5px 14px", borderRadius:"999px", marginBottom:"18px", letterSpacing:"0.06em"}}>
                TRIBUNAL RISK · POLICY REWRITER · COMPREHENSION AI · BOARD REPORTS
              </div>
              <h1 style={{fontSize:"38px", fontWeight:"800", color:"#f8fafc", margin:"0 0 14px", lineHeight:"1.15", letterSpacing:"-0.03em"}}>
                HR Policy Intelligence<br/><span style={{color:gold}}>Platform</span>
              </h1>
              <p style={{fontSize:"15px", color:"rgba(255,255,255,0.4)", margin:0, lineHeight:"1.7", maxWidth:"580px"}}>
                The only platform that combines organisational psychology, ML forecasting, tribunal risk scoring, automatic policy rewriting, and board-ready reporting — in one upload.
              </p>
            </div>

            <div style={{display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:"12px", marginBottom:"16px"}}>
              <div style={card}>
                <span style={lbl}>COMPANY NAME</span>
                <input type="text" placeholder="e.g. Acme Corp" value={companyName} onChange={e=>setCompanyName(e.target.value)}
                  style={{width:"100%", background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.1)", borderRadius:"8px", padding:"10px 12px", color:"#f8fafc", fontSize:"13px", outline:"none", boxSizing:"border-box"}}/>
              </div>
              <div style={card}>
                <span style={lbl}>INDUSTRY</span>
                <select value={industry} onChange={e=>setIndustry(e.target.value)}
                  style={{width:"100%", background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.1)", borderRadius:"8px", padding:"10px 12px", color:"#f8fafc", fontSize:"13px", outline:"none", boxSizing:"border-box"}}>
                  {["Professional Services","Finance & Banking","Technology","Healthcare","Retail","Legal","Manufacturing","Education"].map(i=><option key={i} value={i} style={{background:"#1e293b"}}>{i}</option>)}
                </select>
              </div>
              <div style={card}>
                <span style={lbl}>NO. OF EMPLOYEES</span>
                <input type="number" placeholder="e.g. 250" value={employees} onChange={e=>setEmployees(e.target.value)}
                  style={{width:"100%", background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.1)", borderRadius:"8px", padding:"10px 12px", color:"#f8fafc", fontSize:"13px", outline:"none", boxSizing:"border-box"}}/>
              </div>
            </div>

            <div onDrop={handleDrop} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)}
              style={{border:dragging?`2px dashed ${gold}`:"2px dashed rgba(255,255,255,0.1)", borderRadius:"20px", padding:"56px 24px", textAlign:"center", background:dragging?"rgba(201,168,76,0.04)":"rgba(255,255,255,0.01)", transition:"all 0.2s", marginBottom:"16px"}}>
              <div style={{width:"56px", height:"56px", background:"rgba(201,168,76,0.08)", border:"1px solid rgba(201,168,76,0.15)", borderRadius:"16px", margin:"0 auto 18px", display:"flex", alignItems:"center", justifyContent:"center", fontSize:"26px"}}>📄</div>
              <p style={{color:"rgba(255,255,255,0.6)", fontSize:"15px", margin:"0 0 6px", fontWeight:"600"}}>Drop your HR policy document</p>
              <p style={{color:"rgba(255,255,255,0.2)", fontSize:"12px", margin:"0 0 22px"}}>PDF, DOCX, or TXT — Analysis begins instantly</p>
              <label style={{cursor:"pointer"}}>
                <span style={{background:`linear-gradient(135deg,${gold},#f0d080)`, color:"#0f172a", fontSize:"13px", fontWeight:"800", padding:"11px 28px", borderRadius:"10px"}}>Browse files</span>
                <input type="file" accept=".pdf,.docx,.txt" style={{display:"none"}} onChange={e=>setFile(e.target.files[0])}/>
              </label>
              {file && <div style={{marginTop:"18px"}}><span style={{fontSize:"13px", color:gold, background:"rgba(201,168,76,0.08)", padding:"5px 14px", borderRadius:"999px", border:"1px solid rgba(201,168,76,0.2)"}}>{file.name}</span></div>}
            </div>

            {file && (
              <button onClick={handleTranslate} style={{width:"100%", background:`linear-gradient(135deg,${gold},#f0d080)`, color:"#0f172a", padding:"16px", borderRadius:"12px", fontSize:"15px", fontWeight:"800", border:"none", cursor:"pointer", marginBottom:"28px"}}>
                Run Full Intelligence Analysis — 19 AI Models
              </button>
            )}

            <div style={{display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:"10px", marginBottom:"16px"}}>
              {[
                {icon:"⚖️", label:"Tribunal Risk Score", desc:"Case likelihood + cost"},
                {icon:"✍️", label:"Auto Policy Rewriter", desc:"AI rewrites instantly"},
                {icon:"🧩", label:"Comprehension AI", desc:"Who understands it"},
                {icon:"🏆", label:"Competitor Benchmark", desc:"vs industry leaders"},
                {icon:"💰", label:"Retention ROI", desc:"5-year projection"},
                {icon:"📋", label:"Regulatory Alerts", desc:"Latest law changes"},
                {icon:"🌍", label:"10 Languages", desc:"Auto translation"},
                {icon:"📊", label:"Board Report", desc:"Executive ready"},
                {icon:"📉", label:"Turnover Forecast", desc:"ML 6-month model"},
                {icon:"🧠", label:"Burnout Prediction", desc:"Trajectory curve"},
                {icon:"🔍", label:"Bias Detector", desc:"Exclusion flags"},
                {icon:"🎯", label:"DEI Scorecard", desc:"6 dimensions"},
              ].map(f=>(
                <div key={f.label} style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.06)", borderRadius:"12px", padding:"12px", textAlign:"center"}}>
                  <div style={{fontSize:"20px", marginBottom:"5px"}}>{f.icon}</div>
                  <div style={{fontSize:"11px", color:"rgba(255,255,255,0.5)", fontWeight:"500", marginBottom:"2px"}}>{f.label}</div>
                  <div style={{fontSize:"10px", color:"rgba(255,255,255,0.2)"}}>{f.desc}</div>
                </div>
              ))}
            </div>

            <div style={{display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:"10px"}}>
              {[{label:"Avg tribunal cost prevented", value:"£87,500"},{label:"Productivity recovered", value:"£187,400/yr"},{label:"Policy rewrite ROI", value:"119x"}].map(s=>(
                <div key={s.label} style={{background:"rgba(255,255,255,0.02)", border:"1px solid rgba(255,255,255,0.05)", borderRadius:"10px", padding:"16px", textAlign:"center"}}>
                  <div style={{fontSize:"22px", fontWeight:"700", color:gold, marginBottom:"4px"}}>{s.value}</div>
                  <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>{s.label}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {subStatus === "active" && status === "loading" && (
          <div style={{...card, textAlign:"center", padding:"72px 24px"}}>
            <div style={{width:"44px", height:"44px", border:`3px solid rgba(201,168,76,0.15)`, borderTop:`3px solid ${gold}`, borderRadius:"50%", margin:"0 auto 24px", animation:"spin 1s linear infinite"}}/>
            <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
            <p style={{color:"#f8fafc", fontSize:"16px", fontWeight:"600", margin:"0 0 8px"}}>Running 19-model intelligence analysis...</p>
            <p style={{color:"rgba(255,255,255,0.3)", fontSize:"13px", margin:"0 0 28px"}}>This replaces weeks of HR consultant work</p>
            <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:"8px", maxWidth:"440px", margin:"0 auto", textAlign:"left"}}>
              {["Translating to plain language...","Scoring tribunal risk...","Running turnover ML forecast...","Rewriting policy automatically...","Predicting comprehension by segment...","Benchmarking vs competitors...","Calculating retention ROI...","Scanning regulatory changes...","Modelling productivity impact...","Predicting burnout trajectory...","Scoring DEI compliance...","Detecting bias patterns...","Assessing cognitive load...","Calculating absenteeism cost...","Generating board report...","Scoring psychological safety...","Analysing emotional tone...","Checking compliance flags...","Compiling full report..."].map((step,i)=>(
                <div key={i} style={{display:"flex", alignItems:"center", gap:"8px"}}>
                  <div style={{width:"5px", height:"5px", borderRadius:"50%", background:gold, opacity:0.5, flexShrink:0}}/>
                  <span style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>{step}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {subStatus === "active" && status === "error" && (
          <div style={{background:"rgba(239,68,68,0.08)", border:"1px solid rgba(239,68,68,0.2)", borderRadius:"16px", padding:"32px", textAlign:"center"}}>
            <p style={{color:"#fca5a5", fontSize:"14px", margin:"0 0 16px"}}>{error}</p>
            <button onClick={handleReset} style={{background:"none", border:"1px solid rgba(255,255,255,0.15)", color:"rgba(255,255,255,0.5)", padding:"8px 20px", borderRadius:"8px", fontSize:"13px", cursor:"pointer"}}>Try again</button>
          </div>
        )}

        {subStatus === "active" && status === "done" && result && (
          <div>
            <div style={{display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:"10px", marginBottom:"12px"}}>
              <StatCard label="Tribunal risk" value={result.tribunalRisk.score+"/100"} color={result.tribunalRisk.color}/>
              <StatCard label="Productivity loss" value={fmt(result.productivityLoss.annualCostGBP)} color="#ef4444" sub="per year"/>
              <StatCard label="Retention exposure" value={fmt(result.retentionCalculator.totalExposure)} color="#ef4444"/>
              <StatCard label="Policy ROI" value={result.policyROI.roiMultiplier+"x"} color="#10b981"/>
            </div>
            <div style={{display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:"10px", marginBottom:"20px"}}>
              <StatCard label="Psych safety" value={result.psychologicalSafety.score+"/100"} color={result.psychologicalSafety.color}/>
              <StatCard label="DEI score" value={result.deiScorecard.overall+"/100"} color={result.deiScorecard.color}/>
              <StatCard label="Comprehension" value={result.comprehensionPredictor.overallScore+"%"} color={result.comprehensionPredictor.color}/>
              <StatCard label="Competitor rank" value="Bottom 25%" color="#ef4444"/>
            </div>

            <div style={{display:"flex", gap:"4px", marginBottom:"20px", overflowX:"auto", paddingBottom:"6px"}}>
              {tabs.map(tab=>(
                <button key={tab.id} onClick={()=>setActiveTab(tab.id)}
                  style={{padding:"7px 12px", borderRadius:"8px", border:activeTab===tab.id?`1px solid ${gold}`:"1px solid rgba(255,255,255,0.07)", background:activeTab===tab.id?"rgba(201,168,76,0.15)":"rgba(255,255,255,0.03)", color:activeTab===tab.id?gold:"rgba(255,255,255,0.4)", fontSize:"12px", fontWeight:"500", cursor:"pointer", whiteSpace:"nowrap", flexShrink:0}}>
                  {tab.label}
                </button>
              ))}
            </div>

            {activeTab==="summary" && (
              <div>
                <div style={card}>
                  <span style={lbl}>PLAIN-LANGUAGE SUMMARY</span>
                  <p style={{color:"#e2e8f0", fontSize:"14px", lineHeight:"1.85", margin:"0 0 14px"}}>{result.summary}</p>
                  <div style={{display:"flex", gap:"8px", flexWrap:"wrap"}}>
                    {[`Jargon score: ${result.jargonDensity.score}/100`, `Tone: ${result.emotionalTone.dominant}`, `Comprehension: ${result.comprehensionPredictor.overallScore}%`].map((t,i)=>(
                      <span key={i} style={{fontSize:"12px", color:"rgba(255,255,255,0.3)", background:"rgba(255,255,255,0.05)", padding:"3px 10px", borderRadius:"999px"}}>{t}</span>
                    ))}
                  </div>
                </div>
                <div style={card}>
                  <span style={lbl}>JARGON FLAGS</span>
                  <div style={{display:"flex", gap:"8px", flexWrap:"wrap", marginBottom:"10px"}}>
                    {result.jargonDensity.flaggedTerms.map((t,i)=>(
                      <span key={i} style={{fontSize:"12px", background:"rgba(239,68,68,0.1)", border:"1px solid rgba(239,68,68,0.2)", color:"#fca5a5", padding:"3px 10px", borderRadius:"999px"}}>{t}</span>
                    ))}
                  </div>
                </div>
                <div style={card}>
                  <span style={lbl}>EMPLOYEE FAQs</span>
                  <div style={{display:"flex", flexDirection:"column", gap:"14px"}}>
                    {result.faqs.map((faq,i)=>(
                      <div key={i} style={{borderLeft:`2px solid rgba(201,168,76,0.25)`, paddingLeft:"14px"}}>
                        <p style={{fontSize:"13px", fontWeight:"600", color:"#f8fafc", margin:"0 0 4px"}}>{faq.q}</p>
                        <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:0, lineHeight:"1.6"}}>{faq.a}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {activeTab==="tribunal" && (
              <div>
                <div style={card}>
                  <span style={lbl}>EMPLOYMENT TRIBUNAL RISK SCORE</span>
                  <div style={{display:"flex", alignItems:"center", gap:"20px", marginBottom:"20px"}}>
                    <div style={{width:"90px", height:"90px", borderRadius:"50%", border:`4px solid ${result.tribunalRisk.color}`, display:"flex", alignItems:"center", justifyContent:"center", flexDirection:"column", flexShrink:0}}>
                      <span style={{fontSize:"28px", fontWeight:"800", color:result.tribunalRisk.color}}>{result.tribunalRisk.score}</span>
                      <span style={{fontSize:"10px", color:"rgba(255,255,255,0.3)"}}>/100</span>
                    </div>
                    <div>
                      <div style={{fontSize:"18px", fontWeight:"700", color:result.tribunalRisk.color, marginBottom:"6px"}}>{result.tribunalRisk.label}</div>
                      <div style={{fontSize:"13px", color:"rgba(255,255,255,0.4)", marginBottom:"4px"}}>Avg case cost: <span style={{color:"#ef4444", fontWeight:"600"}}>{fmt(result.tribunalRisk.estimatedCost)}</span></div>
                      <div style={{fontSize:"13px", color:"rgba(255,255,255,0.4)"}}>Time to resolve: <span style={{color:"#f59e0b", fontWeight:"600"}}>{result.tribunalRisk.timeToResolve}</span></div>
                    </div>
                  </div>
                  <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.tribunalRisk.insight}</p>
                  <span style={lbl}>CASE TYPE RISK BREAKDOWN</span>
                  {result.tribunalRisk.cases.map((c,i)=>(
                    <div key={i} style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"14px", marginBottom:"10px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"8px"}}>
                        <div>
                          <p style={{fontSize:"13px", fontWeight:"600", color:"#f8fafc", margin:"0 0 3px"}}>{c.type}</p>
                          <span style={{fontSize:"11px", color:"rgba(255,255,255,0.25)"}}>{c.law}</span>
                        </div>
                        <div style={{textAlign:"right"}}>
                          <div style={{fontSize:"18px", fontWeight:"700", color:c.likelihood>70?"#ef4444":c.likelihood>50?"#f59e0b":"#10b981"}}>{c.likelihood}%</div>
                          <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>{fmt(c.avgCost)} avg</div>
                        </div>
                      </div>
                      <Bar value={c.likelihood} color={c.likelihood>70?"#ef4444":c.likelihood>50?"#f59e0b":"#10b981"} height={6}/>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab==="rewriter" && (
              <div>
                <div style={card}>
                  <span style={lbl}>AI POLICY REWRITER</span>
                  <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:"16px", marginBottom:"20px"}}>
                    <div style={{background:"rgba(239,68,68,0.06)", border:"1px solid rgba(239,68,68,0.15)", borderRadius:"12px", padding:"16px"}}>
                      <div style={{fontSize:"11px", fontWeight:"600", color:"#fca5a5", marginBottom:"10px", letterSpacing:"0.05em"}}>ORIGINAL — READABILITY {result.policyRewriter.readabilityBefore}/100</div>
                      <p style={{fontSize:"13px", color:"rgba(255,255,255,0.5)", lineHeight:"1.7", margin:0}}>{result.policyRewriter.original}</p>
                    </div>
                    <div style={{background:"rgba(16,185,129,0.06)", border:"1px solid rgba(16,185,129,0.15)", borderRadius:"12px", padding:"16px"}}>
                      <div style={{fontSize:"11px", fontWeight:"600", color:"#6ee7b7", marginBottom:"10px", letterSpacing:"0.05em"}}>AI REWRITTEN — READABILITY {result.policyRewriter.readabilityAfter}/100</div>
                      <p style={{fontSize:"13px", color:"rgba(255,255,255,0.7)", lineHeight:"1.7", margin:0}}>{result.policyRewriter.rewritten}</p>
                    </div>
                  </div>
                  <span style={lbl}>IMPROVEMENTS MADE</span>
                  <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:"8px"}}>
                    {result.policyRewriter.improvements.map((imp,i)=>(
                      <div key={i} style={{background:"rgba(16,185,129,0.08)", border:"1px solid rgba(16,185,129,0.15)", borderRadius:"8px", padding:"10px 14px", display:"flex", justifyContent:"space-between", alignItems:"center"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)"}}>{imp.type}</span>
                        <span style={{fontSize:"14px", fontWeight:"700", color:"#6ee7b7"}}>×{imp.count}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {activeTab==="comprehension" && (
              <div>
                <div style={card}>
                  <span style={lbl}>EMPLOYEE COMPREHENSION PREDICTOR</span>
                  <div style={{display:"flex", alignItems:"center", gap:"20px", marginBottom:"16px"}}>
                    <div style={{width:"80px", height:"80px", borderRadius:"50%", border:`4px solid ${result.comprehensionPredictor.color}`, display:"flex", alignItems:"center", justifyContent:"center", flexDirection:"column", flexShrink:0}}>
                      <span style={{fontSize:"24px", fontWeight:"800", color:result.comprehensionPredictor.color}}>{result.comprehensionPredictor.overallScore}%</span>
                    </div>
                    <div>
                      <div style={{fontSize:"16px", fontWeight:"600", color:result.comprehensionPredictor.color, marginBottom:"4px"}}>{result.comprehensionPredictor.label}</div>
                      <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:0, lineHeight:"1.6"}}>{result.comprehensionPredictor.insight}</p>
                    </div>
                  </div>
                  <div style={{background:"rgba(245,158,11,0.08)", border:"1px solid rgba(245,158,11,0.2)", borderRadius:"10px", padding:"14px", marginBottom:"20px"}}>
                    <p style={{fontSize:"12px", color:"#fcd34d", margin:0, lineHeight:"1.6", fontStyle:"italic"}}>{result.comprehensionPredictor.riskStatement}</p>
                  </div>
                  <span style={lbl}>COMPREHENSION BY EMPLOYEE SEGMENT</span>
                  {result.comprehensionPredictor.segments.map((seg,i)=>(
                    <div key={i} style={{marginBottom:"14px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)"}}>{seg.group} <span style={{color:"rgba(255,255,255,0.25)"}}>({seg.size} of workforce)</span></span>
                        <span style={{fontSize:"12px", fontWeight:"600", color:seg.comprehension>60?"#10b981":seg.comprehension>40?"#f59e0b":"#ef4444"}}>{seg.comprehension}%</span>
                      </div>
                      <Bar value={seg.comprehension} color={seg.comprehension>60?"#10b981":seg.comprehension>40?"#f59e0b":"#ef4444"} height={8}/>
                    </div>
                  ))}
                  <div style={{marginTop:"20px", background:"rgba(16,185,129,0.06)", border:"1px solid rgba(16,185,129,0.15)", borderRadius:"10px", padding:"14px", display:"flex", justifyContent:"space-between", alignItems:"center"}}>
                    <span style={{fontSize:"13px", color:"rgba(255,255,255,0.5)"}}>After AI rewrite, comprehension rises to</span>
                    <span style={{fontSize:"22px", fontWeight:"700", color:"#10b981"}}>{result.comprehensionPredictor.afterRewrite}%</span>
                  </div>
                </div>
              </div>
            )}

            {activeTab==="competitor" && (
              <div>
                <div style={card}>
                  <span style={lbl}>COMPETITOR POLICY BENCHMARK</span>
                  <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.competitorBenchmark.insight}</p>
                  {result.competitorBenchmark.competitors.map((c,i)=>(
                    <div key={i} style={{marginBottom:"12px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px", alignItems:"center"}}>
                        <div style={{display:"flex", alignItems:"center", gap:"8px"}}>
                          <span style={{fontSize:"13px", color:c.isYou?"#f8fafc":"rgba(255,255,255,0.45)", fontWeight:c.isYou?"600":"400"}}>{c.name}</span>
                          {c.isYou && <span style={{fontSize:"10px", background:"rgba(201,168,76,0.15)", color:gold, padding:"2px 7px", borderRadius:"999px", fontWeight:"600"}}>YOU</span>}
                        </div>
                        <span style={{fontSize:"12px", fontWeight:"600", color:c.isYou?gold:"rgba(255,255,255,0.4)"}}>{c.score}/100</span>
                      </div>
                      <Bar value={c.score} color={c.isYou?gold:c.score>70?"#10b981":c.score>50?"#f59e0b":"rgba(255,255,255,0.15)"} height={c.isYou?10:6}/>
                    </div>
                  ))}
                  <div style={{marginTop:"20px", background:"rgba(239,68,68,0.06)", border:"1px solid rgba(239,68,68,0.15)", borderRadius:"10px", padding:"14px"}}>
                    <p style={{fontSize:"13px", color:"#fca5a5", margin:0, lineHeight:"1.6"}}>{result.competitorBenchmark.talentImpact}</p>
                  </div>
                </div>
                <div style={card}>
                  <span style={lbl}>INDUSTRY METRICS BENCHMARK</span>
                  {result.industryBenchmark.metrics.map((m,i)=>(
                    <div key={i} style={{marginBottom:"16px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)"}}>{m.name}</span>
                        <div style={{display:"flex", gap:"10px"}}>
                          <span style={{fontSize:"12px", color:m.yours>m.benchmark?"#ef4444":"#10b981", fontWeight:"700"}}>You: {m.yours}{m.unit}</span>
                          <span style={{fontSize:"12px", color:"rgba(255,255,255,0.25)"}}>Avg: {m.benchmark}{m.unit}</span>
                        </div>
                      </div>
                      <div style={{position:"relative", height:"8px"}}>
                        <Bar value={Math.min(m.yours,100)} color={m.yours>m.benchmark?"#ef4444":"#10b981"} height={8}/>
                        <div style={{position:"absolute", top:0, left:`${Math.min(m.benchmark,100)}%`, width:"2px", height:"8px", background:"rgba(255,255,255,0.4)", borderRadius:"1px"}}/>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab==="retention" && (
              <div>
                <div style={card}>
                  <span style={lbl}>RETENTION COST CALCULATOR</span>
                  <div style={{display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:"10px", marginBottom:"20px"}}>
                    <div style={{background:"rgba(239,68,68,0.08)", border:"1px solid rgba(239,68,68,0.15)", borderRadius:"10px", padding:"14px", textAlign:"center"}}>
                      <div style={{fontSize:"22px", fontWeight:"700", color:"#ef4444"}}>{result.retentionCalculator.currentRetentionRate}%</div>
                      <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)", marginTop:"4px"}}>Current retention</div>
                    </div>
                    <div style={{background:"rgba(16,185,129,0.08)", border:"1px solid rgba(16,185,129,0.15)", borderRadius:"10px", padding:"14px", textAlign:"center"}}>
                      <div style={{fontSize:"22px", fontWeight:"700", color:"#10b981"}}>{result.retentionCalculator.afterPolicyRewrite.retentionRate}%</div>
                      <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)", marginTop:"4px"}}>After rewrite</div>
                    </div>
                    <div style={{background:"rgba(201,168,76,0.08)", border:"1px solid rgba(201,168,76,0.15)", borderRadius:"10px", padding:"14px", textAlign:"center"}}>
                      <div style={{fontSize:"22px", fontWeight:"700", color:gold}}>{fmt(result.retentionCalculator.afterPolicyRewrite.costSaved)}</div>
                      <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)", marginTop:"4px"}}>Annual saving</div>
                    </div>
                  </div>
                  <span style={lbl}>5-YEAR COST PROJECTION</span>
                  {result.retentionCalculator.fiveYearProjection.map((y,i)=>(
                    <div key={i} style={{display:"flex", alignItems:"center", gap:"12px", marginBottom:"10px"}}>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.4)", width:"48px", flexShrink:0}}>{y.year}</span>
                      <div style={{flex:1}}>
                        <div style={{display:"flex", gap:"4px", marginBottom:"3px"}}>
                          <div style={{flex:y.withPolicy, background:"rgba(239,68,68,0.4)", height:"8px", borderRadius:"4px 0 0 4px"}}/>
                          <div style={{flex:y.withRewrite, background:"rgba(16,185,129,0.4)", height:"8px", borderRadius:"0 4px 4px 0"}}/>
                        </div>
                      </div>
                      <div style={{display:"flex", gap:"8px", flexShrink:0}}>
                        <span style={{fontSize:"11px", color:"#ef4444"}}>{fmt(y.withPolicy)}</span>
                        <span style={{fontSize:"11px", color:"#10b981"}}>{fmt(y.withRewrite)}</span>
                      </div>
                    </div>
                  ))}
                  <div style={{display:"flex", gap:"16px", marginTop:"8px"}}>
                    <div style={{display:"flex", alignItems:"center", gap:"6px"}}><div style={{width:"12px", height:"8px", background:"rgba(239,68,68,0.4)", borderRadius:"2px"}}/><span style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>Current policy cost</span></div>
                    <div style={{display:"flex", alignItems:"center", gap:"6px"}}><div style={{width:"12px", height:"8px", background:"rgba(16,185,129,0.4)", borderRadius:"2px"}}/><span style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>After rewrite cost</span></div>
                  </div>
                </div>
              </div>
            )}

            {activeTab==="regulatory" && (
              <div style={card}>
                <span style={lbl}>REGULATORY CHANGE ALERTS</span>
                <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.regulatoryAlerts.insight}</p>
                {result.regulatoryAlerts.upcoming.map((law,i)=>(
                  <div key={i} style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"12px", padding:"16px", marginBottom:"12px", borderLeft:`3px solid ${law.impact==="High"?"#ef4444":"#f59e0b"}`}}>
                    <div style={{display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:"8px"}}>
                      <div style={{flex:1, marginRight:"12px"}}>
                        <p style={{fontSize:"13px", fontWeight:"600", color:"#f8fafc", margin:"0 0 4px"}}>{law.law}</p>
                        <span style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>Effective: {law.effective}</span>
                      </div>
                      <span style={{fontSize:"11px", fontWeight:"700", padding:"3px 10px", borderRadius:"999px", background:law.impact==="High"?"rgba(239,68,68,0.15)":"rgba(245,158,11,0.15)", color:law.impact==="High"?"#fca5a5":"#fcd34d", whiteSpace:"nowrap"}}>{law.impact} impact</span>
                    </div>
                    <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:0, lineHeight:"1.6"}}>{law.description}</p>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="languages" && (
              <div style={card}>
                <span style={lbl}>MULTI-LANGUAGE TRANSLATION</span>
                <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.multiLanguage.insight}</p>
                <span style={lbl}>ESTIMATED WORKFORCE LANGUAGE BREAKDOWN</span>
                {result.multiLanguage.workforceLanguages.map((lang,i)=>(
                  <div key={i} style={{marginBottom:"12px"}}>
                    <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                      <span style={{fontSize:"13px", color:"rgba(255,255,255,0.5)"}}>{lang.language}</span>
                      <span style={{fontSize:"13px", fontWeight:"600", color:lang.language==="English"?"#10b981":gold}}>{lang.percentage}%</span>
                    </div>
                    <Bar value={lang.percentage*1.5} color={lang.language==="English"?"#10b981":gold} height={6}/>
                  </div>
                ))}
                <span style={{...lbl, marginTop:"20px"}}>AVAILABLE TRANSLATIONS</span>
                <div style={{display:"flex", gap:"8px", flexWrap:"wrap", marginBottom:"16px"}}>
                  {result.multiLanguage.supported.map((lang,i)=>(
                    <div key={i} style={{background:"rgba(201,168,76,0.08)", border:"1px solid rgba(201,168,76,0.15)", color:gold, fontSize:"12px", padding:"5px 12px", borderRadius:"999px", cursor:"pointer"}}>{lang}</div>
                  ))}
                </div>
                <div style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"14px", textAlign:"center"}}>
                  <p style={{fontSize:"13px", color:"rgba(255,255,255,0.4)", margin:"0 0 12px"}}>Full translation available on Pro plan</p>
                  <button style={{background:`linear-gradient(135deg,${gold},#f0d080)`, color:"#0f172a", border:"none", padding:"10px 24px", borderRadius:"8px", fontSize:"13px", fontWeight:"700", cursor:"pointer"}}>Upgrade to translate</button>
                </div>
              </div>
            )}

            {activeTab==="board" && (
              <div style={card}>
                <div style={{display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:"20px"}}>
                  <span style={lbl}>BOARD-READY EXECUTIVE REPORT</span>
                  <div style={{display:"flex", gap:"8px"}}>
                    <span style={{fontSize:"11px", background:"rgba(239,68,68,0.12)", color:"#fca5a5", padding:"3px 8px", borderRadius:"999px"}}>{result.boardReport.classification}</span>
                    <span style={{fontSize:"11px", background:"rgba(255,255,255,0.06)", color:"rgba(255,255,255,0.4)", padding:"3px 8px", borderRadius:"999px"}}>{result.boardReport.preparedFor}</span>
                  </div>
                </div>
                <div style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"12px", padding:"18px", marginBottom:"16px"}}>
                  <p style={{fontSize:"14px", color:"rgba(255,255,255,0.6)", margin:0, lineHeight:"1.7", fontStyle:"italic"}}>{result.boardReport.executiveSummary}</p>
                </div>
                <span style={lbl}>KEY RISKS FOR BOARD</span>
                {result.boardReport.keyRisks.map((risk,i)=>(
                  <div key={i} style={{display:"flex", justifyContent:"space-between", alignItems:"center", background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"14px", marginBottom:"8px"}}>
                    <div>
                      <p style={{fontSize:"13px", fontWeight:"600", color:"#f8fafc", margin:"0 0 3px"}}>{risk.risk}</p>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.35)"}}>{risk.financial}</span>
                    </div>
                    <span style={{fontSize:"11px", fontWeight:"700", padding:"3px 10px", borderRadius:"999px", background:risk.urgency==="Immediate"?"rgba(239,68,68,0.15)":"rgba(245,158,11,0.15)", color:risk.urgency==="Immediate"?"#fca5a5":"#fcd34d", whiteSpace:"nowrap"}}>{risk.urgency}</span>
                  </div>
                ))}
                <div style={{marginTop:"20px", background:"rgba(16,185,129,0.06)", border:"1px solid rgba(16,185,129,0.2)", borderRadius:"12px", padding:"18px"}}>
                  <p style={{fontSize:"11px", fontWeight:"600", color:"#6ee7b7", marginBottom:"8px", letterSpacing:"0.05em"}}>BOARD RECOMMENDATION</p>
                  <p style={{fontSize:"14px", color:"rgba(255,255,255,0.7)", margin:0, lineHeight:"1.7"}}>{result.boardReport.recommendation}</p>
                </div>
                <button onClick={handleDownload} style={{width:"100%", marginTop:"16px", background:`linear-gradient(135deg,${gold},#f0d080)`, color:"#0f172a", padding:"14px", borderRadius:"10px", fontSize:"14px", fontWeight:"800", border:"none", cursor:"pointer"}}>
                  Download Full Board Report
                </button>
              </div>
            )}

            {activeTab==="forecast" && (
              <div>
                <div style={card}>
                  <span style={lbl}>TURNOVER ML FORECAST — 6 MONTHS</span>
                  <div style={{display:"flex", alignItems:"center", gap:"16px", marginBottom:"16px"}}>
                    <div style={{fontSize:"36px", fontWeight:"800", color:result.turnoverPrediction.color}}>{result.turnoverPrediction.riskScore}<span style={{fontSize:"16px"}}>/100</span></div>
                    <div>
                      <div style={{fontSize:"16px", fontWeight:"600", color:result.turnoverPrediction.color, marginBottom:"4px"}}>{result.turnoverPrediction.label}</div>
                      <div style={{fontSize:"13px", color:"rgba(255,255,255,0.4)"}}>Projected loss: <span style={{color:"#ef4444", fontWeight:"600"}}>{fmt(result.turnoverPrediction.projectedLoss)}</span></div>
                    </div>
                  </div>
                  <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.turnoverPrediction.insight}</p>
                  {result.turnoverPrediction.forecast.map((m,i)=>(
                    <div key={i} style={{marginBottom:"12px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.45)"}}>{m.month}</span>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.35)"}}>{m.employees} at risk · <span style={{color:m.risk>60?"#ef4444":m.risk>40?"#f59e0b":"#10b981", fontWeight:"600"}}>{m.risk}%</span></span>
                      </div>
                      <Bar value={m.risk} color={m.risk>60?"#ef4444":m.risk>40?"#f59e0b":"#10b981"} height={8}/>
                    </div>
                  ))}
                </div>
                <div style={card}>
                  <span style={lbl}>ABSENTEEISM COST FORECAST</span>
                  <div style={{display:"flex", alignItems:"baseline", gap:"12px", marginBottom:"16px"}}>
                    <div style={{fontSize:"32px", fontWeight:"700", color:"#ef4444"}}>{fmt(result.absenteeismForecast.annualCostGBP)}</div>
                    <div style={{fontSize:"13px", color:"rgba(255,255,255,0.35)"}}>projected annual cost</div>
                  </div>
                  {result.absenteeismForecast.monthlyForecast.map((m,i)=>(
                    <div key={i} style={{display:"flex", alignItems:"center", gap:"12px", marginBottom:"8px"}}>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.4)", width:"32px"}}>{m.month}</span>
                      <div style={{flex:1}}><Bar value={m.rate*7} color={m.rate>10?"#ef4444":m.rate>8?"#f59e0b":"#10b981"} height={6}/></div>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)", width:"32px", textAlign:"right"}}>{m.rate}%</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab==="productivity" && (
              <div style={card}>
                <span style={lbl}>PRODUCTIVITY LOSS ANALYSIS</span>
                <div style={{display:"flex", alignItems:"baseline", gap:"12px", marginBottom:"16px"}}>
                  <div style={{fontSize:"36px", fontWeight:"800", color:"#ef4444"}}>{fmt(result.productivityLoss.annualCostGBP)}</div>
                  <div style={{fontSize:"14px", color:"rgba(255,255,255,0.4)"}}>estimated annual loss</div>
                </div>
                <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.productivityLoss.insight}</p>
                <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:"10px", marginBottom:"20px"}}>
                  <div style={{background:"rgba(239,68,68,0.08)", border:"1px solid rgba(239,68,68,0.15)", borderRadius:"10px", padding:"14px", textAlign:"center"}}>
                    <div style={{fontSize:"24px", fontWeight:"700", color:"#ef4444"}}>{result.productivityLoss.current}%</div>
                    <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)", marginTop:"4px"}}>Current productivity</div>
                  </div>
                  <div style={{background:"rgba(16,185,129,0.08)", border:"1px solid rgba(16,185,129,0.15)", borderRadius:"10px", padding:"14px", textAlign:"center"}}>
                    <div style={{fontSize:"24px", fontWeight:"700", color:"#10b981"}}>{result.productivityLoss.potential}%</div>
                    <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)", marginTop:"4px"}}>Potential after rewrite</div>
                  </div>
                </div>
                {result.productivityLoss.breakdown.map((b,i)=>(
                  <div key={i} style={{marginBottom:"14px"}}>
                    <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)", maxWidth:"70%"}}>{b.cause}</span>
                      <span style={{fontSize:"12px", color:"#ef4444", fontWeight:"600"}}>{fmt(b.costGBP)}</span>
                    </div>
                    <Bar value={b.loss*2.5} color="#ef4444" height={6}/>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="burnout" && (
              <div style={card}>
                <span style={lbl}>BURNOUT TRAJECTORY FORECAST</span>
                <div style={{display:"flex", alignItems:"center", gap:"16px", marginBottom:"16px"}}>
                  <div style={{fontSize:"36px", fontWeight:"800", color:result.burnoutForecast.color}}>{result.burnoutForecast.currentRisk}<span style={{fontSize:"16px"}}>/100</span></div>
                  <div>
                    <div style={{fontSize:"14px", color:"rgba(255,255,255,0.5)", marginBottom:"2px"}}>Peak at <span style={{color:result.burnoutForecast.color, fontWeight:"600"}}>{result.burnoutForecast.peakMonth}</span></div>
                    <div style={{fontSize:"14px", color:"rgba(255,255,255,0.5)"}}><span style={{color:"#f59e0b", fontWeight:"600"}}>{result.burnoutForecast.affectedEmployees} employees</span> in high-risk zone</div>
                  </div>
                </div>
                <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.burnoutForecast.insight}</p>
                {result.burnoutForecast.trajectory.map((t,i)=>(
                  <div key={i} style={{marginBottom:"12px"}}>
                    <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.45)"}}>{t.period}</span>
                      <span style={{fontSize:"12px", fontWeight:"600", color:t.score>75?"#ef4444":t.score>60?"#f59e0b":"#10b981"}}>{t.score}/100</span>
                    </div>
                    <Bar value={t.score} color={t.score>75?"#ef4444":t.score>60?"#f59e0b":"#10b981"} height={8}/>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="morale" && (
              <div style={card}>
                <span style={lbl}>TEAM MORALE INDEX</span>
                <div style={{display:"flex", alignItems:"center", gap:"16px", marginBottom:"20px"}}>
                  <div style={{width:"80px", height:"80px", borderRadius:"50%", border:`4px solid ${result.teamMoraleIndex.color}`, display:"flex", alignItems:"center", justifyContent:"center", flexDirection:"column", flexShrink:0}}>
                    <span style={{fontSize:"24px", fontWeight:"800", color:result.teamMoraleIndex.color}}>{result.teamMoraleIndex.overall}</span>
                    <span style={{fontSize:"10px", color:"rgba(255,255,255,0.3)"}}>/100</span>
                  </div>
                  <div>
                    <div style={{fontSize:"18px", fontWeight:"700", color:result.teamMoraleIndex.color}}>{result.teamMoraleIndex.label}</div>
                    <div style={{fontSize:"13px", color:"rgba(255,255,255,0.4)", marginTop:"4px"}}>Based on Amy Edmondson psychological safety framework</div>
                  </div>
                </div>
                <span style={lbl}>DIMENSIONS vs INDUSTRY BENCHMARK</span>
                {result.teamMoraleIndex.dimensions.map((d,i)=>(
                  <div key={i} style={{marginBottom:"16px"}}>
                    <div style={{display:"flex", justifyContent:"space-between", marginBottom:"6px"}}>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)"}}>{d.name}</span>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.35)"}}>
                        <span style={{color:d.score<d.benchmark?"#ef4444":"#10b981", fontWeight:"600"}}>{d.score}</span>
                        <span style={{color:"rgba(255,255,255,0.2)"}}> vs {d.benchmark} avg</span>
                      </span>
                    </div>
                    <div style={{position:"relative"}}>
                      <Bar value={d.score} color={d.score<50?"#ef4444":d.score<65?"#f59e0b":"#10b981"} height={8}/>
                      <div style={{position:"absolute", top:0, left:`${d.benchmark}%`, width:"2px", height:"8px", background:"rgba(255,255,255,0.3)", borderRadius:"1px"}}/>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="dei" && (
              <div style={card}>
                <span style={lbl}>DEI COMPLIANCE SCORECARD</span>
                <div style={{display:"flex", alignItems:"center", gap:"16px", marginBottom:"20px"}}>
                  <div style={{fontSize:"36px", fontWeight:"800", color:result.deiScorecard.color}}>{result.deiScorecard.overall}<span style={{fontSize:"16px"}}>/100</span></div>
                  <div style={{fontSize:"16px", color:result.deiScorecard.color, fontWeight:"600"}}>{result.deiScorecard.label}</div>
                </div>
                {result.deiScorecard.categories.map((c,i)=>(
                  <div key={i} style={{marginBottom:"14px"}}>
                    <div style={{display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"5px"}}>
                      <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)"}}>{c.name}</span>
                      <div style={{display:"flex", alignItems:"center", gap:"8px"}}>
                        <span style={{fontSize:"11px", padding:"2px 8px", borderRadius:"999px", background:c.status==="fail"?"rgba(239,68,68,0.12)":c.status==="partial"?"rgba(245,158,11,0.12)":"rgba(16,185,129,0.12)", color:c.status==="fail"?"#fca5a5":c.status==="partial"?"#fcd34d":"#6ee7b7"}}>{c.status}</span>
                        <span style={{fontSize:"12px", fontWeight:"600", color:c.score<40?"#ef4444":c.score<60?"#f59e0b":"#10b981"}}>{c.score}/100</span>
                      </div>
                    </div>
                    <Bar value={c.score} color={c.score<40?"#ef4444":c.score<60?"#f59e0b":"#10b981"} height={6}/>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="cognitive" && (
              <div>
                <div style={card}>
                  <span style={lbl}>COGNITIVE LOAD INDEX BY DEPARTMENT</span>
                  <div style={{display:"flex", alignItems:"baseline", gap:"12px", marginBottom:"8px"}}>
                    <div style={{fontSize:"32px", fontWeight:"800", color:result.cognitiveLoad.color}}>{result.cognitiveLoad.overall}/100</div>
                    <div style={{fontSize:"15px", color:result.cognitiveLoad.color}}>{result.cognitiveLoad.label} Cognitive Load</div>
                  </div>
                  <p style={{fontSize:"13px", color:"rgba(255,255,255,0.4)", margin:"0 0 20px", lineHeight:"1.6"}}>{result.cognitiveLoad.insight}</p>
                  {result.cognitiveLoad.departments.map((d,i)=>(
                    <div key={i} style={{marginBottom:"14px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"5px"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.5)"}}>{d.name}</span>
                        <span style={{fontSize:"12px", fontWeight:"600", color:d.color}}>{d.load}/100</span>
                      </div>
                      <Bar value={d.load} color={d.color} height={8}/>
                    </div>
                  ))}
                </div>
                <div style={card}>
                  <span style={lbl}>LEADERSHIP RISK ASSESSMENT</span>
                  <div style={{display:"flex", alignItems:"center", gap:"12px", marginBottom:"16px"}}>
                    <div style={{fontSize:"28px", fontWeight:"700", color:result.leadershipRisk.color}}>{result.leadershipRisk.score}/100</div>
                    <div style={{fontSize:"14px", color:result.leadershipRisk.color}}>{result.leadershipRisk.label}</div>
                  </div>
                  {result.leadershipRisk.risks.map((r,i)=>(
                    <div key={i} style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"12px 14px", marginBottom:"8px", display:"flex", justifyContent:"space-between", alignItems:"center"}}>
                      <div>
                        <p style={{fontSize:"13px", color:"rgba(255,255,255,0.6)", margin:"0 0 3px"}}>{r.area}</p>
                        <span style={{fontSize:"11px", padding:"2px 7px", borderRadius:"999px", background:r.impact==="Critical"?"rgba(239,68,68,0.12)":"rgba(245,158,11,0.12)", color:r.impact==="Critical"?"#fca5a5":"#fcd34d"}}>{r.impact}</span>
                      </div>
                      <div style={{textAlign:"right"}}>
                        <div style={{fontSize:"18px", fontWeight:"700", color:r.likelihood>70?"#ef4444":r.likelihood>50?"#f59e0b":"#10b981"}}>{r.likelihood}%</div>
                        <div style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>likelihood</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab==="psychology" && (
              <div>
                <div style={card}>
                  <span style={lbl}>PSYCHOLOGICAL SAFETY SCORE</span>
                  <div style={{display:"flex", alignItems:"center", gap:"20px", marginBottom:"16px"}}>
                    <div style={{width:"80px", height:"80px", borderRadius:"50%", border:`4px solid ${result.psychologicalSafety.color}`, display:"flex", alignItems:"center", justifyContent:"center", flexDirection:"column", flexShrink:0}}>
                      <span style={{fontSize:"24px", fontWeight:"700", color:result.psychologicalSafety.color}}>{result.psychologicalSafety.score}</span>
                      <span style={{fontSize:"10px", color:"rgba(255,255,255,0.3)"}}>/100</span>
                    </div>
                    <div>
                      <div style={{fontSize:"18px", fontWeight:"600", color:result.psychologicalSafety.color, marginBottom:"4px"}}>{result.psychologicalSafety.label}</div>
                      <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:0, lineHeight:"1.6", maxWidth:"400px"}}>{result.psychologicalSafety.insight}</p>
                    </div>
                  </div>
                  {result.psychologicalSafety.recommendations.map((r,i)=>(
                    <div key={i} style={{display:"flex", gap:"10px", alignItems:"flex-start", marginBottom:"10px"}}>
                      <div style={{width:"6px", height:"6px", borderRadius:"50%", background:gold, marginTop:"5px", flexShrink:0}}/>
                      <p style={{fontSize:"13px", color:"rgba(255,255,255,0.5)", margin:0, lineHeight:"1.6"}}>{r}</p>
                    </div>
                  ))}
                </div>
                <div style={card}>
                  <span style={lbl}>EMOTIONAL TONE ANALYSIS</span>
                  <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:"0 0 16px", lineHeight:"1.6"}}>{result.emotionalTone.insight}</p>
                  {result.emotionalTone.scores.map((s,i)=>(
                    <div key={i} style={{marginBottom:"12px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"4px"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.45)"}}>{s.label}</span>
                        <span style={{fontSize:"12px", color:s.color, fontWeight:"600"}}>{s.value}%</span>
                      </div>
                      <Bar value={s.value} color={s.color}/>
                    </div>
                  ))}
                </div>
                <div style={card}>
                  <span style={lbl}>SECTION COMPLEXITY HEATMAP</span>
                  {result.complexitySections.map((sec,i)=>(
                    <div key={i} style={{marginBottom:"12px"}}>
                      <div style={{display:"flex", justifyContent:"space-between", marginBottom:"4px"}}>
                        <span style={{fontSize:"12px", color:"rgba(255,255,255,0.45)"}}>{sec.title}</span>
                        <span style={{fontSize:"12px", color:sec.color, fontWeight:"600"}}>{sec.complexity}/100</span>
                      </div>
                      <Bar value={sec.complexity} color={sec.color} height={8}/>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab==="compliance" && (
              <div style={card}>
                <span style={lbl}>COMPLIANCE RISK FLAGS</span>
                <div style={{display:"flex", alignItems:"center", gap:"12px", marginBottom:"20px"}}>
                  <div style={{fontSize:"36px", fontWeight:"800", color:result.complianceRisk.color}}>{result.complianceRisk.score}/100</div>
                  <div style={{fontSize:"16px", color:result.complianceRisk.color, fontWeight:"600"}}>{result.complianceRisk.label}</div>
                </div>
                {result.complianceRisk.flags.map((flag,i)=>(
                  <div key={i} style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"14px", marginBottom:"10px", borderLeft:`3px solid ${flag.severity==="high"?"#ef4444":flag.severity==="medium"?"#f59e0b":"#6b7280"}`}}>
                    <div style={{display:"flex", gap:"8px", marginBottom:"6px"}}>
                      <span style={{fontSize:"10px", fontWeight:"700", padding:"2px 8px", borderRadius:"999px", background:flag.severity==="high"?"rgba(239,68,68,0.15)":flag.severity==="medium"?"rgba(245,158,11,0.15)":"rgba(107,114,128,0.15)", color:flag.severity==="high"?"#fca5a5":flag.severity==="medium"?"#fcd34d":"#9ca3af", textTransform:"uppercase"}}>{flag.severity}</span>
                      <span style={{fontSize:"11px", color:"rgba(255,255,255,0.3)"}}>{flag.law}</span>
                    </div>
                    <p style={{fontSize:"13px", color:"rgba(255,255,255,0.55)", margin:0}}>{flag.issue}</p>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="bias" && (
              <div style={card}>
                <span style={lbl}>BIAS & EXCLUSION ANALYSIS</span>
                <div style={{display:"flex", alignItems:"center", gap:"12px", marginBottom:"20px"}}>
                  <div style={{fontSize:"36px", fontWeight:"800", color:result.biasAnalysis.color}}>{result.biasAnalysis.score}/100</div>
                  <div style={{fontSize:"16px", color:result.biasAnalysis.color, fontWeight:"600"}}>{result.biasAnalysis.label}</div>
                </div>
                {result.biasAnalysis.findings.map((f,i)=>(
                  <div key={i} style={{background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"16px", marginBottom:"10px"}}>
                    <p style={{fontSize:"13px", fontWeight:"600", color:"#f59e0b", margin:"0 0 6px"}}>{f.type}</p>
                    <p style={{fontSize:"13px", color:"rgba(255,255,255,0.45)", margin:0, lineHeight:"1.6"}}>{f.detail}</p>
                  </div>
                ))}
              </div>
            )}

            {activeTab==="improve" && (
              <div style={card}>
                <span style={lbl}>AI-RECOMMENDED IMPROVEMENTS</span>
                {result.improvements.map((item,i)=>(
                  <div key={i} style={{display:"flex", gap:"12px", alignItems:"flex-start", background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)", borderRadius:"10px", padding:"14px", marginBottom:"10px"}}>
                    <span style={{fontSize:"10px", fontWeight:"700", padding:"3px 8px", borderRadius:"999px", background:item.priority==="High"?"rgba(239,68,68,0.15)":item.priority==="Medium"?"rgba(245,158,11,0.15)":"rgba(107,114,128,0.15)", color:item.priority==="High"?"#fca5a5":item.priority==="Medium"?"#fcd34d":"#9ca3af", whiteSpace:"nowrap", marginTop:"2px"}}>{item.priority}</span>
                    <p style={{fontSize:"13px", color:"rgba(255,255,255,0.55)", margin:0, lineHeight:"1.6"}}>{item.action}</p>
                  </div>
                ))}
              </div>
            )}

            <div style={{display:"flex", gap:"10px", marginTop:"8px"}}>
              <button onClick={handleCopy} style={{flex:1, background:`linear-gradient(135deg,${gold},#f0d080)`, color:"#0f172a", padding:"13px", borderRadius:"10px", fontSize:"13px", fontWeight:"800", border:"none", cursor:"pointer"}}>{copied?"Copied!":"Copy summary"}</button>
              <button onClick={handleDownload} style={{flex:1, background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.12)", color:"#f8fafc", padding:"13px", borderRadius:"10px", fontSize:"13px", fontWeight:"600", cursor:"pointer"}}>Download report</button>
              <button onClick={handleReset} style={{flex:1, background:"rgba(255,255,255,0.04)", border:"1px solid rgba(255,255,255,0.08)", color:"rgba(255,255,255,0.4)", padding:"13px", borderRadius:"10px", fontSize:"13px", fontWeight:"600", cursor:"pointer"}}>New policy</button>
            </div>
          </div>
        )}

        <div style={{textAlign:"center", marginTop:"48px", paddingTop:"24px", borderTop:"1px solid rgba(255,255,255,0.05)"}}>
          <p style={{fontSize:"12px", color:"rgba(255,255,255,0.15)", margin:0}}>Powered by <span style={{color:gold}}>PsychFlo</span> · Organisational Psychology + ML Forecasting + AI Engineering</p>
        </div>
      </div>
    </div>
  );
}
