"use client";
import { useRouter } from "next/navigation";
import Nav from "../components/Nav";

const gold = "#c9a84c";
const purple = "#c4b5fd";

const STEPS = [
  {
    number: "01",
    phase: "Diagnose",
    title: "Run a 5-minute Workforce Risk Diagnostic",
    desc: "Answer 9 questions about your organisation's people challenges — headcount, industry, biggest retention risks, manager confidence, and compliance concerns. No spreadsheets. No consultants. No prep required.",
    detail: "The diagnostic maps your answers against three risk categories: Workforce Risk Detection, Retention & Burnout Prevention, and Manager & Culture Intelligence. Each category is scored 0–100 based on your inputs.",
    color: "#fca5a5",
    bg: "rgba(239,68,68,0.06)",
    border: "rgba(239,68,68,0.18)",
    icon: "🔍",
    output: "Your three risk scores + overall risk band (Low / Medium / High)",
  },
  {
    number: "02",
    phase: "Analyse",
    title: "Receive your Executive Workforce Intelligence Report",
    desc: "Within 48 hours of booking an audit, your leadership team receives a board-ready PDF. It maps your risk scores to financial exposure, root causes, and the specific people signals driving each category.",
    detail: "The report is generated by four AI psychology engines running continuously across your people signals — not a static questionnaire output, but a live intelligence layer built on journaling analysis, standup language, onboarding trajectories, and manager behaviour patterns.",
    color: gold,
    bg: "rgba(201,168,76,0.06)",
    border: "rgba(201,168,76,0.2)",
    icon: "📊",
    output: "Board-ready PDF: risk scores, financial exposure, root causes, recommended actions",
  },
  {
    number: "03",
    phase: "Prioritise",
    title: "Get a ranked list of what to fix first",
    desc: "Not every risk requires the same urgency. The Executive Report ranks your three risk categories by financial exposure and time-to-impact — so your leadership team knows exactly where to focus first.",
    detail: "High-risk categories come with a named top issue and a 30-day intervention window. Medium-risk categories have a monitor-and-review protocol. Low-risk categories are documented for compliance evidence.",
    color: purple,
    bg: "rgba(139,92,246,0.06)",
    border: "rgba(139,92,246,0.18)",
    icon: "⚡",
    output: "Prioritised risk register with financial exposure per category",
  },
  {
    number: "04",
    phase: "Act",
    title: "Execute a 30-day plan your team can action immediately",
    desc: "Every report includes a 30-day action plan: specific steps, owners, and week-by-week sequencing. No implementation consultant required. No months-long rollout. Actions your HR lead or COO can start on Monday.",
    detail: "Depending on your risk band, actions range from manager coaching conversations and policy language updates to onboarding check-in cadences and standup restructuring. Each action is tied to the specific signal that generated it.",
    color: "#6ee7b7",
    bg: "rgba(16,185,129,0.06)",
    border: "rgba(16,185,129,0.18)",
    icon: "✅",
    output: "Week-by-week 30-day plan with named owners and success metrics",
  },
];

const ENGINES = [
  { name: "Burnout Early Warning", category: "Retention" },
  { name: "AI Journaling Analysis", category: "Retention" },
  { name: "Daily Pulse Monitor", category: "Retention" },
  { name: "Cognitive Load Index", category: "Retention" },
  { name: "Manager Effectiveness Scoring", category: "Culture" },
  { name: "Manager Coaching Engine", category: "Culture" },
  { name: "Onboarding & Belonging Analytics", category: "Culture" },
  { name: "Grief & Crisis Support", category: "Culture" },
  { name: "Policy Intelligence Review", category: "Risk" },
  { name: "Compliance Audit Engine", category: "Risk" },
  { name: "Async Standup Safety Monitor", category: "Risk" },
  { name: "Psychological Safety Index", category: "Risk" },
];

const categoryColor = { Retention: "#6ee7b7", Culture: purple, Risk: "#fca5a5" };
const categoryBg = { Retention: "rgba(16,185,129,0.08)", Culture: "rgba(139,92,246,0.08)", Risk: "rgba(239,68,68,0.08)" };

export default function HowItWorksPage() {
  const router = useRouter();
  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(135deg,#0a0f1e 0%,#0f172a 40%,#1a0a2e 100%)", fontFamily: "system-ui,-apple-system,sans-serif" }}>
      <Nav />
      <div style={{ maxWidth: "900px", margin: "0 auto", padding: "80px 24px 100px" }}>

        {/* ── Hero ── */}
        <section style={{ textAlign: "center", marginBottom: "80px" }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "rgba(201,168,76,0.08)", border: "1px solid rgba(201,168,76,0.2)", color: gold, fontSize: "11px", fontWeight: "700", padding: "5px 14px", borderRadius: "999px", marginBottom: "24px", letterSpacing: "0.07em" }}>
            HOW IT WORKS
          </div>
          <h1 style={{ fontSize: "46px", fontWeight: "800", color: "#f8fafc", margin: "0 0 20px", lineHeight: "1.08", letterSpacing: "-0.03em" }}>
            From diagnostic to action<br />
            <span style={{ color: gold }}>in 48 hours</span>
          </h1>
          <p style={{ fontSize: "18px", color: "rgba(255,255,255,0.45)", margin: "0 auto 36px", lineHeight: "1.75", maxWidth: "600px" }}>
            PsychFlo turns 9 AI psychology engines into one decision: what to fix first, why, and how — delivered to your leadership team before the week is out.
          </p>
          <button
            onClick={() => router.push("/diagnostic")}
            style={{ background: `linear-gradient(135deg,${gold},#f0d080)`, color: "#0f172a", border: "none", padding: "16px 36px", borderRadius: "12px", fontSize: "15px", fontWeight: "800", cursor: "pointer" }}>
            Run the Diagnostic — Free →
          </button>
        </section>

        {/* ── 4 Steps ── */}
        <section style={{ marginBottom: "80px" }}>
          <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
            {STEPS.map((step, i) => (
              <div key={i} style={{ background: step.bg, border: `1px solid ${step.border}`, borderRadius: "20px", padding: "36px 40px", display: "grid", gridTemplateColumns: "80px 1fr", gap: "32px", alignItems: "flex-start" }}>
                <div style={{ textAlign: "center" }}>
                  <div style={{ fontSize: "32px", marginBottom: "8px" }}>{step.icon}</div>
                  <div style={{ fontSize: "11px", fontWeight: "800", color: step.color, letterSpacing: "0.1em" }}>{step.phase.toUpperCase()}</div>
                  <div style={{ fontSize: "28px", fontWeight: "900", color: "rgba(255,255,255,0.08)", lineHeight: 1, marginTop: "4px" }}>{step.number}</div>
                </div>
                <div>
                  <h2 style={{ fontSize: "20px", fontWeight: "700", color: "#f8fafc", margin: "0 0 10px", letterSpacing: "-0.02em" }}>{step.title}</h2>
                  <p style={{ fontSize: "14px", color: "rgba(255,255,255,0.55)", margin: "0 0 14px", lineHeight: "1.7" }}>{step.desc}</p>
                  <p style={{ fontSize: "13px", color: "rgba(255,255,255,0.35)", margin: "0 0 18px", lineHeight: "1.65" }}>{step.detail}</p>
                  <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: "8px", padding: "8px 14px" }}>
                    <span style={{ color: step.color, fontSize: "12px" }}>▶</span>
                    <span style={{ fontSize: "12px", color: "rgba(255,255,255,0.45)", fontWeight: "500" }}>{step.output}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ── Timeline strip ── */}
        <section style={{ marginBottom: "80px" }}>
          <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "16px", padding: "32px 36px" }}>
            <h2 style={{ fontSize: "18px", fontWeight: "700", color: "#f8fafc", margin: "0 0 24px", letterSpacing: "-0.02em" }}>What the first week looks like</h2>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(5,1fr)", gap: "0" }}>
              {[
                { day: "Day 0", event: "Run diagnostic", sub: "5 minutes" },
                { day: "Day 0", event: "Book audit", sub: "$750 one-time" },
                { day: "Day 1", event: "Engines analyse", sub: "AI processing" },
                { day: "Day 2", event: "Report delivered", sub: "Board-ready PDF" },
                { day: "Day 3", event: "Actions started", sub: "30-day plan live" },
              ].map((t, i) => (
                <div key={i} style={{ textAlign: "center", position: "relative" }}>
                  {i < 4 && (
                    <div style={{ position: "absolute", top: "18px", left: "50%", width: "100%", height: "1px", background: "rgba(201,168,76,0.25)" }} />
                  )}
                  <div style={{ width: "36px", height: "36px", borderRadius: "50%", background: "rgba(201,168,76,0.12)", border: `1px solid rgba(201,168,76,0.3)`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 10px", position: "relative", zIndex: 1 }}>
                    <div style={{ width: "8px", height: "8px", borderRadius: "50%", background: gold }} />
                  </div>
                  <div style={{ fontSize: "11px", fontWeight: "700", color: gold, marginBottom: "3px" }}>{t.day}</div>
                  <div style={{ fontSize: "12px", fontWeight: "600", color: "rgba(255,255,255,0.65)", marginBottom: "2px" }}>{t.event}</div>
                  <div style={{ fontSize: "10px", color: "rgba(255,255,255,0.25)" }}>{t.sub}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── Intelligence engines ── */}
        <section style={{ marginBottom: "80px" }}>
          <h2 style={{ fontSize: "28px", fontWeight: "700", color: "#f8fafc", margin: "0 0 8px", letterSpacing: "-0.02em" }}>The intelligence layer</h2>
          <p style={{ fontSize: "14px", color: "rgba(255,255,255,0.35)", margin: "0 0 28px", maxWidth: "600px", lineHeight: "1.65" }}>
            Twelve AI psychology engines run continuously across your people signals. You never interact with them directly — they surface as risk scores, ranked issues, and actionable recommendations in your Executive Report.
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "10px" }}>
            {ENGINES.map((e, i) => (
              <div key={i} style={{ background: categoryBg[e.category], border: `1px solid ${categoryColor[e.category]}22`, borderRadius: "10px", padding: "14px 16px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px" }}>
                <span style={{ fontSize: "12px", fontWeight: "600", color: "rgba(255,255,255,0.65)" }}>{e.name}</span>
                <span style={{ fontSize: "10px", fontWeight: "700", color: categoryColor[e.category], whiteSpace: "nowrap", flexShrink: 0 }}>{e.category}</span>
              </div>
            ))}
          </div>
        </section>

        {/* ── FAQ ── */}
        <section style={{ marginBottom: "80px" }}>
          <h2 style={{ fontSize: "28px", fontWeight: "700", color: "#f8fafc", margin: "0 0 24px", letterSpacing: "-0.02em" }}>Common questions</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            {[
              {
                q: "How long does the diagnostic take?",
                a: "5 minutes. Nine questions about your organisation — no spreadsheets, no data uploads, no prep. You get your risk scores immediately on completion.",
              },
              {
                q: "What data do you need from us?",
                a: "For the diagnostic: just your answers to the 9 questions. For the full audit: we request access to your HR policy documents, standup logs (if any), and onboarding data. All data is handled under NDA and GDPR-compliant processing.",
              },
              {
                q: "How is this different from an employee survey?",
                a: "Surveys are backward-looking, annual, and self-reported. PsychFlo analyses signals continuously — language patterns, burnout trajectories, manager behaviour, policy exposure — and surfaces risk 6–12 weeks before it becomes a resignation, sick note, or tribunal claim.",
              },
              {
                q: "Do employees know they're being monitored?",
                a: "Yes — all PsychFlo tools are opt-in and fully disclosed to employees. The psychological safety and journaling tools require active employee participation. PsychFlo is designed to be an employee wellbeing tool that also generates leadership intelligence — not surveillance.",
              },
              {
                q: "What happens after the 30-day plan?",
                a: "You can book a follow-up audit to measure improvement, or move to a monthly Growth Prevention System subscription ($2,000/month) for continuous monitoring, quarterly executive reports, and manager coaching support.",
              },
            ].map((faq, i) => (
              <div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "12px", padding: "20px 24px" }}>
                <h3 style={{ fontSize: "14px", fontWeight: "700", color: "rgba(255,255,255,0.8)", margin: "0 0 8px" }}>{faq.q}</h3>
                <p style={{ fontSize: "13px", color: "rgba(255,255,255,0.4)", margin: 0, lineHeight: "1.65" }}>{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── CTA ── */}
        <section>
          <div style={{ background: "rgba(201,168,76,0.06)", border: "1px solid rgba(201,168,76,0.2)", borderRadius: "20px", padding: "52px 48px", textAlign: "center" }}>
            <h2 style={{ fontSize: "28px", fontWeight: "700", color: "#f8fafc", margin: "0 0 12px", letterSpacing: "-0.02em" }}>
              Start with the diagnostic — it's free
            </h2>
            <p style={{ fontSize: "15px", color: "rgba(255,255,255,0.4)", margin: "0 auto 32px", maxWidth: "480px", lineHeight: "1.7" }}>
              5 minutes to your three workforce risk scores. No signup required. Book the full audit only if the scores warrant it.
            </p>
            <div style={{ display: "flex", gap: "12px", justifyContent: "center", flexWrap: "wrap", marginBottom: "14px" }}>
              <button
                onClick={() => router.push("/diagnostic")}
                style={{ background: `linear-gradient(135deg,${gold},#f0d080)`, color: "#0f172a", border: "none", padding: "15px 32px", borderRadius: "10px", fontSize: "15px", fontWeight: "800", cursor: "pointer" }}>
                Run the Diagnostic →
              </button>
              <button
                onClick={() => router.push("/pricing")}
                style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.12)", color: "rgba(255,255,255,0.7)", padding: "15px 28px", borderRadius: "10px", fontSize: "14px", fontWeight: "600", cursor: "pointer" }}>
                See Pricing →
              </button>
            </div>
            <p style={{ fontSize: "12px", color: "rgba(255,255,255,0.2)", margin: 0 }}>Diagnostic is free · Audit delivered in 48 hours · No lock-in</p>
          </div>
        </section>

      </div>
    </div>
  );
}
